import Head from 'next/head'

export const Head_ = () => (
  <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />

    <meta charSet="utf-8" />
    <meta name="description" content="プリコネRのプロフカードの作成ツール" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@JADENgygo" />
    <meta property="og:url" content="https://priconne-profile.vercel.app" />
    <meta property="og:title" content="プリコネプロフ" />
    <meta property="og:description" content="プリコネRのプロフカードの作成ツール" />
    <meta property="og:image" content="https://priconne-profile.vercel.app/img/peko.png" />
    <link rel="icon" href="/img/peko.png" />
    <title>プリコネプロフ</title>
  </Head>
);
