name: Docker Image CI

on:
  push:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - run: |
          sudo apt-get update
          sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - run: yarn dev &
      - run: npm test
      - if: success()
        run: |
          message=$(git log --oneline -n 1 | sed -E 's/^\S+ (.+)/\1/')
          gh pr create --title "${message}" --body "自動生成プルリクエスト" --base master
          gh pr merge --merge
      - if: always()
        uses: actions/upload-artifact@v2
        with:
          path: cypress
